# this apigroup is available from 1.14 onwards
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: $(NAME)
  labels:
    app.kubernetes.io/name: $(NAME)
    app.kubernetes.io/component: ingress
    app.kubernetes.io/part-of: $(ID)
    app.kubernetes.io/managed-by: payara-cloud
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    cert-manager.io/cluster-issuer: letsencrypt
    cert-manager.io/acme-challenge-type: http01
spec:
  tls:
  - hosts:
    - $(PROJECT)-$(STAGE).$(DOMAIN)
    secretName: tls.$(PROJECT)-$(STAGE).$(DOMAIN)
  rules:
  - host: $(PROJECT)-$(STAGE).$(DOMAIN)
    http:
      paths:
      - path: $(PATH)
        backend:
          serviceName: $(NAME)
          servicePort: 80